name: currency_app
description: A new Flutter application that contains the currency graphs


version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  xml: ^3.5.0
  http: ^0.12.0+2
  xml2json: ^4.0.0
  convert: ^2.1.1
  backdrop: ^0.1.8
  intl: ^0.16.0
  charts_flutter: ^0.8.1
  rxdart: ^0.22.5
  provider: ^3.1.0+1


  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:


  uses-material-design: true
